### ISSUE TITLE
Beta version should not be tagged as "latest"

### ISSUE THREAD

**Issue by F30** [grafana/grafana-docker#131]
On Dockerhub, the "latest" tag currently points to the container for 5.0.0-beta1. This means that when pulling the container with "latest" or no version specified, you will get a beta version.

In my humble opinion, "latest" should only give you released versions.

**Comment by bergquist** [comment]
@F30 Thank you for noticing. We are terribly sorry for this. Looking into our build scripts for found the bug that caused this. The problem is that there is no good way of solving this. We are faced with two options
* Keep it as is.
* Point lastest at 4.6.3 

Pointing latest at 4.6.3 again would be problematic for those would start a new container with the same tag and get an old version since 5.0 dashboards are not supported in 4.6.3. 

Considering 5.0 stable is just two weeks away we think that keeping 5.0.0-beta1 as latest would cause the least amounts of problem. What do you think?

**Comment by DanCech** [comment]
@bergquist I think that's the only reasonable approach.  I'd also be keen to see :beta and :nightly tags available for those who want to use them.

**Comment by bergquist** [comment]
@DanCech `master` is kind of the same as `nightly`. But I think people are more familiar with the `nightly` term so that makes sense. A `beta` tag should be possible once we start improving the build. 

I'm currently writing down the goals we want to achieve when we start working on improving the build in https://github.com/grafana/grafana/issues/9633
